apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: OWNER-doggos
  labels:
    app: doggos
    owner: OWNER
spec:
  template:
    metadata:
      labels:
        app: doggos
        tier: web
        owner: OWNER
    spec:
      containers:
      - name: doggos
        image: gcr.io/windmill-public-containers/servantes/doggos
        command: ["/go/bin/doggos"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/doggos/web/templates"
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: OWNER-doggos
  labels:
    app: doggos
    owner: OWNER
spec:
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
  selector:
    app: doggos
    owner: OWNER
