apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: doggos
  labels:
    app: doggos
spec:
  template:
    metadata:
      labels:
        app: doggos
        tier: web
    spec:
      containers:
      - name: doggos
        image: windmill.build/servantes/doggos
        command: ["/go/bin/doggos"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/doggos/web/templates"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: doggos
  labels:
    app: doggos
spec:
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
  selector:
    app: doggos