apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: OWNER-hypothesizer
  labels:
    app: hypothesizer
    owner: OWNER
spec:
  template:
    metadata:
      labels:
        app: hypothesizer
        tier: web
        owner: OWNER
    spec:
      containers:
      - name: hypothesizer
        image: gcr.io/windmill-public-containers/servantes/hypothesizer
        command: ["python", "/app/app.py"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: OWNER-hypothesizer
  labels:
    app: hypothesizer
    owner: OWNER
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: hypothesizer
    owner: OWNER
