apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-fortune
  labels:
    app: fortune
    varowner: varowner
spec:
  selector:
    matchLabels:
      app: fortune
      varowner: varowner
  template:
    metadata:
      labels:
        app: fortune
        tier: web
        varowner: varowner
    spec:
      containers:
      - name: fortune
        image: gcr.io/windmill-public-containers/servantes/fortune
        command: ["/go/bin/fortune"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/fortune/web/templates"
        - name: THE_SECRET
          valueFrom:
            secretKeyRef:
              name: varowner-servantes-stuff
              key: things
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "10m"
