apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: OWNER-snack
  labels:
    app: snack
    owner: OWNER
spec:
  template:
    metadata:
      labels:
        app: snack
        tier: web
        owner: OWNER
    spec:
      containers:
      - name: snack
        image: gcr.io/windmill-public-containers/servantes/snack
        command: ["/go/bin/snack"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/snack/web/templates"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: OWNER-snack
  labels:
    app: snack
    owner: OWNER
spec:
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
  selector:
    app: snack
    owner: OWNER
