apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: OWNER-fe
  labels:
    app: fe
    owner: OWNER
spec:
  template:
    metadata:
      labels:
        app: fe
        tier: web
        owner: OWNER
    spec:
      containers:
      - name: fe
        image: gcr.io/windmill-public-containers/servantes/fe
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/fe/web/templates"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: OWNER-fe
  labels:
    app: fe
    owner: OWNER
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: fe
    owner: OWNER
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
- kind: User
  name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
