apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-fortune
  labels:
    app: fortune
    owner: varowner
spec:
  selector:
    matchLabels:
      app: fortune
      owner: varowner
  template:
    metadata:
      labels:
        app: fortune
        tier: web
        owner: varowner
    spec:
      containers:
      - name: fortune
        image: fortune
        command: ["/go/bin/fortune"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/tilt-dev/servantes/fortune/web/templates"
        - name: THE_SECRET
          valueFrom:
            secretKeyRef:
              name: varowner-servantes-stuff
              key: things
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "10m"
