apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tick
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 90
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tick
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo tick
          restartPolicy: OnFailure
