// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/fortune.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Fortune struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fortune) Reset()         { *m = Fortune{} }
func (m *Fortune) String() string { return proto.CompactTextString(m) }
func (*Fortune) ProtoMessage()    {}
func (*Fortune) Descriptor() ([]byte, []int) {
	return fileDescriptor_fortune_512846caacddf77b, []int{0}
}
func (m *Fortune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fortune.Unmarshal(m, b)
}
func (m *Fortune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fortune.Marshal(b, m, deterministic)
}
func (dst *Fortune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fortune.Merge(dst, src)
}
func (m *Fortune) XXX_Size() int {
	return xxx_messageInfo_Fortune.Size(m)
}
func (m *Fortune) XXX_DiscardUnknown() {
	xxx_messageInfo_Fortune.DiscardUnknown(m)
}

var xxx_messageInfo_Fortune proto.InternalMessageInfo

func (m *Fortune) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Fortune)(nil), "api.Fortune")
}

func init() { proto.RegisterFile("api/fortune.proto", fileDescriptor_fortune_512846caacddf77b) }

var fileDescriptor_fortune_512846caacddf77b = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0xc8, 0xd4,
	0x4f, 0xcb, 0x2f, 0x2a, 0x29, 0xcd, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e,
	0x2c, 0xc8, 0x54, 0x92, 0xe5, 0x62, 0x77, 0x83, 0x88, 0x0a, 0x09, 0x71, 0xb1, 0x94, 0xa4, 0x56,
	0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0xa5, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x80, 0x9f, 0xf0, 0x3f, 0x00, 0x00, 0x00,
}
