apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: OWNER-spoonerisms
  labels:
    app: spoonerisms
    owner: OWNER
spec:
  template:
    metadata:
      labels:
        app: spoonerisms
        tier: web
        owner: OWNER
    spec:
      containers:
      - name: spoonerisms
        image: gcr.io/windmill-public-containers/servantes/spoonerisms
        command: ["node", "/app/index.js"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: OWNER-spoonerisms
  labels:
    app: spoonerisms
    owner: OWNER
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: spoonerisms
    owner: OWNER
