apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: OWNER-vigoda
  labels:
    app: vigoda
    owner: OWNER
spec:
  template:
    metadata:
      labels:
        app: vigoda
        tier: web
        owner: OWNER
    spec:
      containers:
      - name: vigoda
        image: gcr.io/windmill-public-containers/servantes/vigoda
        command: ["/go/bin/vigoda"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/vigoda/web/templates"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: OWNER-vigoda
  labels:
    app: vigoda
    owner: OWNER
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: vigoda
    owner: OWNER
